#!/usr/bin/env php
<?php
/**
 * Tinker: A Symfony console application that doesn't really do anything. Yet?
 *
 * @author Jeremy Ward <jeremy@jmichaelward.com
 * @package JMW\Tinker
 */

namespace JMW\Tinker;

use Symfony\Component\Console\Application;

$autoload = __DIR__ . '/vendor/autoload.php';

if (!is_readable($autoload)) {
    echo "Could not find autoloader. Tinker out.\n";
    return;
}

require_once $autoload;

$app = new Application(Config::APP_NAME, Config::APP_VERSION);

(new Tinker($app))->registerCommands();

$app->run();
